package:
  name: conda-env
  version: 2.5.0esss

build:
  number: 0
  string: 0
  preserve_egg_dir: yes
  always_include_files:
    - bin/activate              [unix]
    - Scripts/activate.bat      [win]
    - bin/deactivate            [unix]
    - Scripts/deactivate.bat    [win]

source:
  git_url: ../

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - conda env
    - conda env -h
    - conda env list -h
    - conda env create -h
    - conda env export -h
    - conda env remove -h

about:
  home: https://github.com/conda/conda-env/
